# Site
repository: lorne-luo/lorne-luo.github.io.git
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Lorne Luo
title: Python Data Engineer / DevOps
email: dev@luotao.net
website: http://cv.luotao.net

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username: lorne-luo
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: lorne-luo
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be

# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's <b>Lorne</B>, a senior <mark>Python Data Engineer</mark> / <mark>DevOps Engineer</mark>.
  
  I am :
  - One of the earliest <mark>Python</mark> developers in Australia since `2015`
  - Over 15 years of extensive software development experience spanning many popular programming languages.
  - Enthusiastic coder with `100+` non-forked Github repos, average [`1k commits per year`](/images/github_commits.png){:target="_blank"} alongside full-time job
  - Full-Stack Plus developer experienced in Frontend/Backend web development, Data Engineering/Science, and DevOps
  - AI embracer currently running a YouTube channel featuring videos automatically generated by AI technologies such as ChatGPT, Whisper, Stable Diffusion, UVR5, Real-ESRGAN, Wav2lip etc

content:
  - title: EMPLOYMENT # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Leighton O’Brien / Titan Cloud
        link: cv.luotao.net/employment/lob/
        link_text: <u>Check Showcases</u>
        sub_title: Senior Data Engineer / DevOps
        caption: Apr 2020 - May 2024
        quote: >
          Industry-leading provider of fuel software analytics and field technologies, serving 20k+ fuel station across the world, billions IoT records ingestion per month.
        description: | # this will include new lines to allow paragraphs
          - DevOps on a global market-oriented data ETL pipeline in petroleum industry which processes billion IoT records per month
          - Renew outdated data ETL workflows with a series of modern techs and provide high-quality, continuous delivery
          - Managed 80+ EC2 servers, including server access control, OS/package version upgrades, vulnerability fix and urgent problem solving
          - Support the whole team as export of <mark>Python</mark>, <mark>Linux</mark>, and <mark>Open-Source</mark> community
          - Worked with primary data scientist to implement a Python-based Proof-of-Concept for complex analytical and mathematical intellectual property
          - Web development on both backend and frontend for report purpose API and portal

      - layout: left
        title: Butterfly
        link: cv.luotao.net/employment/butterfly/
        link_text: <u>Check Showcases</u>
        sub_title: Senior Full Stack Developer
        caption: Jul 2017 - Apr 2020
        quote: >
          A leading web development agency in Australia demonstrated by the 64 website design awards.
        description: | # this will include new lines to allow paragraphs
          - Develop solution and implement high-value international web applications as prime back end developer
          - Follow up end to end process of SDLC including BA, coding, testing, /CD and hotfix on cloud base environment
          - Support the whole team as expert of Python and backend development
          - Sustain and manage reusable libraries and maintain a standard initialization repository.
          - <mark>Fire fighter</mark> for urgent deadline and thorny project
          - Hosted an <mark>Opensource-Insight</mark> channel in team's Slack

      - layout: left
        title: Combitel
        # link: combitel.com.au
        # link_text: boringcompany.com
        sub_title: Full Stack Developer
        caption: Mar 2015 - Feb 2017
        quote: >
          Provide large scale, high-availability complete IPTV package solution
        description: | # this will include new lines to allow paragraphs
          - Dev/Ops for IPTV middleware which provide multimedia content management and delivery to multiple devices.
          - Focused on seansirvice-side architecture design and programming.

  - title: FULL-TIME JOB PROJECTS # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Enterprise Petroleum Service(iHub)
        link: https://www.leightonobrien.com/wp-content/uploads/2023/09/iHUB-flyer-Leighton-OBrien-Fuel-Management.pdf
        link_text: Product Brochure
        quote: >
          EPS is a comprehensive petroleum industry service solution include real-time inventory statistic, alarm management and monitoring & reporting, backed with AWS based data pipline which process millions IoT data per day.
        description: | # this will include new lines to allow paragraphs
          - Proposed and established a <mark>Airflow</mark> cluster with 7 nodes, replaced `600+` Python2 cronjobs to Python3 DAGs
          - Integrated <mark>Auth0</mark> authentication with `3` production services for `6` clients, migrated hundreds users
          - Worked with primary data scientist to implement a proof-of-concept demo with <mark>Pandas</mark>, <mark>Numpy</mark>, <mark>Matplotlib</mark> for analytical/mathematical intensive IP
          - Maintain CI/CD pipelines which using <mark>Jenkins</mark> <mark>Github Action</mark> <mark>Shell</mark> <mark>Powershell</mark> <mark>Kubernetes</mark> <mark>Terraform</mark> <mark>Cloudformation</mark>
          - Managed and monitored `80+` Linux EC2 servers, utilizing <mark>Ansible</mark> <mark>Puppet</mark> <mark>Icinga</mark> <mark>Grafana</mark> <mark>Prometheus</mark> <mark>Statd</mark>
          - Designed and finished a centralized clients metadata management system on serverless architecture, provide both webui and API
          - `10+` featured tech-oriented wiki pages and skill share presentations, below are some slides:
            - [<u>Advanced Git</u>](https://docs.google.com/presentation/d/e/2PACX-1vRt0M-7vtCmvnr38hKsjtzPE1Y_uIedUxbZwFv-3BIEvH9NB0rFe8OzvNzzcQ_DJdPWeMwJbVLbZPys/pub?start=false&loop=false&delayms=3000){:target="_blank"}
            - [<u>TDD and How to</u>](https://docs.google.com/presentation/d/e/2PACX-1vTNimnu1UlgmVXTyRTLg1xI37UNUqADgQXLFSvhc6d0cz9Bo9_hbWxd-vIXTGhOFjL5Q_55Ji1AKWlH/pub?start=true&loop=false&delayms=5000){:target="_blank"}

      - layout: left
        title: <a href="https://butterfly.com.au/our-work/monash-fodmap/" target="_blank">Monash Fodmap</a>
        link: monashfodmap.com
        quote: >
          International official website of Monash University Low FODMAP Diet, including public site, blog, e-commerce, course enrollment system and recipe certification system.

        description: | # this will include new lines to allow paragraphs
          - Start as contractor, finished `60%` codes of this million dollar valued project in `6` months
          - Implement a [<u>Two-way data sync</u>](https://docs.google.com/presentation/d/e/2PACX-1vSUn19vIDP0XTwxM_WibMHKXU26tHldlbuZrbjUi3DBNfSqu1tJHqAMajzdEFslms0wWJMa5Ab9AlPd/pub?start=true&loop=false&delayms=5000) between <mark>Django</mark> and <mark>Salesforce</mark> for eCommerce platform
          - Coding for kernel logic of complicated recipe certification workflow
          - Leverage finite state machine, auto programming to accelerate dev
          - Concluded a life-cycle through [<u>Automated Model-Driven Development Methodology</u>](https://docs.google.com/presentation/d/e/2PACX-1vQShyly1wlMnR4KGB9BBwjDhMtRTSxumuteNmZyFN1CqQVPZlzPClQdoqiRL5LsSATXB6KWwCS6g9J7/pub?start=true&loop=false&delayms=3000) which reduced development resource `20%-40%` for new projects

      - layout: left
        title: Reform Clothing
        link: reformclothing.com
        quote: >
          Makes high-quality custom-made apparel from design to delivery.

        description: |
          - Fine-tune <mark>Django DRF</mark> API performance, reduced around `95%` response time
          - Finish complicated [<u>Custom Apparel Designer</u>](https://www.reformclothing.com/au/design-lab/R1044?designId=498HYPTY4S&primary=%23171717&secondary=%2398989A) in <mark>React</mark>
          - Implement solution to get real time callback from Salesforce sync middleware

      - layout: left
        title: OmniScreen Pilot
        link: omniscreen.com.au
        quote: >
          An enterprise TV and digital signage application server which can be provided as an appliance or can be deployed in the Cloud as a SaaS offering..

        description: |
          - Finish distributed tv device management by <mark>Django</mark> + <mark>Celery</mark>
          - Implement <mark>FFmpeg</mark> encoding for media files and EPG streaming process
          - Create CI/CD pipeline with <mark>Jenkins</mark>, <mark>Docker</mark> and <mark>Salt-stack</mark>

  - title: PERSONAL PROJECTS # Title for the section
    layout: list # Type of content section (list/text)
    content:

      - layout: left
        title: Hawkeye
        link: hawkeye.luotao.net
        quote: >
          A weekly decision making system for ASX share stock investment which is using <mark>Monte Carlo stochastic</mark> approach to calculate return-risk balanced ranking.

        description: |
          - Tech stacks: <mark>Python</mark>, <mark>Kiness</mark>, <mark>Airflow</mark>, <mark>DynamoDB</mark>, <mark>Lambda</mark>, <mark>Redis</mark>, <mark>Django</mark>, <mark>TA-Lib</mark>, <mark>Pandas</mark>, <mark>Numpy</mark>, <mark>Matplotlib</mark>, <mark>Seaborn</mark>
          - [<u>Screenshots</u>](/images/hawkeye.png){:target="_blank"}
#          ![Hawkeye](/images/hawkeye.png "Hawkeye")

      - layout: left
        title: QSForex
        link:
        quote: >
          Event-driven Forex trading platform which support tick-level price streaming, support pluggable strategy, instant notification, order history.

        description: |
          - Event-driven architecture with, which support tick-level price streaming and pluggable event handler
          - Well defined interface which could replace Forex broker easily
          - Leverage [<u>machine learning algorithms like a data scientist</u>](http://j.luotao.net/notebooks/forex/mark1/3_training_and_optimazation.ipynb) to develop trading strategy
          - Tech Stacks: <mark>Python</mark>, <mark>EC2</mark>, <mark>Jupyter</mark>, <mark>TA-Lib</mark>, <mark>Pandas</mark>, <mark>Numpy</mark>, <mark>Matplotlib</mark>, <mark>Sklearn</mark>, <mark>optunity</mark>, <mark>keras</mark>

      - layout: left
        title: OZSales
        link: s.luotao.net
        quote: >
          Multi-tenants online order and logistics tracing management system include customer, order, delivery, tracking and reporting.

        description: |
          - Fully featured E-commerce order management system by <mark>Django</mark>, <mark>Celery</mark>, <mark>Postgres</mark> and <mark>Vue.js</mark>
          - [<u>Screenshots</u>](/images/ozsales.png){:target="_blank"}
#          ![ozsales](/images/ozsales.png "ozsales")
          

  - title: EDUCATION # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Beihang University, China
        caption: 2010 - 2014
        sub_title: Software Engineering, PhD
        quote: >
          Top 3 computer science university in China.
        description: | # this will include new lines to allow paragraphs
          After 4 years study, I quited due to migrating to Australia.
      - layout: left
        title: Hebei University of Technology, China
        caption: 2007 - 2010
        sub_title: Software Engineering, MS


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside software engineering, some of my other interests and hobbies are:
      - [<u>Photography</u>](https://www.dreamstime.com/luotao_info#res6109850){:target="_blank"}
      - [<u>Youtube Channel</u>](https://www.youtube.com/@user-yg1zb6xb3j/videos){:target="_blank"}
      - [<u>Snowboard</u>](https://youtu.be/w4rGUOMeu8I){:target="_blank"}
      - [<u>Drone Aerial Filming</u>](https://youtu.be/Xm2Yx8Oiwvc){:target="_blank"}

#      Look at this cool image
#      ![Trees](/images/landscape-trees.jpg "Trees"){:target="_blank"}


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

